version: '2'
services:

  doc:
    restart: unless-stopped
    image: amireldor/croc.doc
    ports:
      - "5000:5000" #FIXME: remove, temp for testing
    depends_on:
      - mongo

  mongo:
    restart: unless-stopped
    image: mongo:3.2
    volumes:
      - /home/amir/croc.mongo:/data/db
